### PR TITLE
basic_ec2

### PR DESCRIPTION
**Pull request by rcclemente**
Atlantis test

### CODE REVIEW

**Comment by rcclemente** [comment]
Ran Plan for dir: `basic_ec2` workspace: `default`

**Plan Error**
```
running "/usr/local/bin/terraform init -input=false -no-color -upgrade" in "/home/atlantis/.atlantis/repos/rcclemente/terraform-atlantis-infra/1/default/basic_ec2": exit status 1

Initializing the backend...

Successfully configured the backend "s3"! Terraform will automatically
use this backend unless the backend configuration changes.
Error refreshing state: AccessDenied: Access Denied
	status code: 403, request id: 48ED0D64E6FC2AAC, host id: t9/9yBwxFe3eFFUk6L/bWgC/U1sFYONSenhDL926m70Do3di7XmQj/uwdaYJWHWJKy0NQ12sS9k=

```

**Comment by rcclemente** [comment]
atlantis plan

**Comment by rcclemente** [comment]
Ran Plan for dir: `basic_ec2` workspace: `default`

**Plan Error**
```
running "/usr/local/bin/terraform init -input=false -no-color -upgrade" in "/home/atlantis/.atlantis/repos/rcclemente/terraform-atlantis-infra/1/default/basic_ec2": exit status 1

Initializing the backend...
Error refreshing state: AccessDenied: Access Denied
	status code: 403, request id: BC8AD3AD56249B77, host id: rk53lLzMnqoFRg4d0QTplzcL5UkkQd8ET1VyihZkRvMij2r4EthSbrjAQB0WdCaxY2ZCgqyHWLs=

```

**Comment by rcclemente** [comment]
atlantis plan

**Comment by rcclemente** [comment]
atlantis plan

**Comment by rcclemente** [comment]
Ran Plan for dir: `basic_ec2` workspace: `default`

```diff

No changes. Infrastructure is up-to-date.

This means that Terraform did not detect any differences between your
configuration and real physical resources that exist. As a result, no
actions need to be performed.

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d basic_ec2`
* :put_litter_in_its_place: To **delete** this plan click [here](https://atlantis.kojie.cyou/lock?id=rcclemente%252Fterraform-atlantis-infra%252Fbasic_ec2%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -d basic_ec2`

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by rcclemente** [comment]
**Plan Error**
```
parsing atlantis.yaml: repo config not allowed to set 'workflow' key: server-side config needs 'allowed_overrides: [workflow]'
```

**Comment by rcclemente** [comment]
atlantis plan

**Comment by rcclemente** [comment]
Ran Plan for dir: `basic_ec2` workspace: `default`

<details><summary>Show Output</summary>

```diff

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
+ create

Terraform will perform the following actions:

  # aws_instance.web will be created
+ resource "aws_instance" "web" {
      + ami                          = "ami-0b786a1a999c4e98e"
      + arn                          = (known after apply)
      + associate_public_ip_address  = (known after apply)
      + availability_zone            = (known after apply)
      + cpu_core_count               = (known after apply)
      + cpu_threads_per_core         = (known after apply)
      + get_password_data            = false
      + host_id                      = (known after apply)
      + id                           = (known after apply)
      + instance_state               = (known after apply)
      + instance_type                = "t2.micro"
      + ipv6_address_count           = (known after apply)
      + ipv6_addresses               = (known after apply)
      + key_name                     = (known after apply)
      + network_interface_id         = (known after apply)
      + outpost_arn                  = (known after apply)
      + password_data                = (known after apply)
      + placement_group              = (known after apply)
      + primary_network_interface_id = (known after apply)
      + private_dns                  = (known after apply)
      + private_ip                   = (known after apply)
      + public_dns                   = (known after apply)
      + public_ip                    = (known after apply)
      + security_groups              = (known after apply)
      + source_dest_check            = true
      + subnet_id                    = (known after apply)
      + tags                         = {
          + "Name" = "HelloWorld"
        }
      + tenancy                      = (known after apply)
      + volume_tags                  = (known after apply)
      + vpc_security_group_ids       = (known after apply)

      + ebs_block_device {
          + delete_on_termination = (known after apply)
          + device_name           = (known after apply)
          + encrypted             = (known after apply)
          + iops                  = (known after apply)
          + kms_key_id            = (known after apply)
          + snapshot_id           = (known after apply)
          + volume_id             = (known after apply)
          + volume_size           = (known after apply)
          + volume_type           = (known after apply)
        }

      + ephemeral_block_device {
          + device_name  = (known after apply)
          + no_device    = (known after apply)
          + virtual_name = (known after apply)
        }

      + metadata_options {
          + http_endpoint               = (known after apply)
          + http_put_response_hop_limit = (known after apply)
          + http_tokens                 = (known after apply)
        }

      + network_interface {
          + delete_on_termination = (known after apply)
          + device_index          = (known after apply)
          + network_interface_id  = (known after apply)
        }

      + root_block_device {
          + delete_on_termination = (known after apply)
          + device_name           = (known after apply)
          + encrypted             = (known after apply)
          + iops                  = (known after apply)
          + kms_key_id            = (known after apply)
          + volume_id             = (known after apply)
          + volume_size           = (known after apply)
          + volume_type           = (known after apply)
        }
    }

Plan: 1 to add, 0 to change, 0 to destroy.

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d basic_ec2`
* :put_litter_in_its_place: To **delete** this plan click [here](https://atlantis.kojie.cyou/lock?id=rcclemente%252Fterraform-atlantis-infra%252Fbasic_ec2%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -d basic_ec2`
</details>

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by rcclemente** [comment]
Ran Plan for dir: `basic_ec2` workspace: `default`

<details><summary>Show Output</summary>

```diff

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
+ create

Terraform will perform the following actions:

  # aws_instance.web will be created
+ resource "aws_instance" "web" {
      + ami                          = "ami-0b786a1a999c4e98e"
      + arn                          = (known after apply)
      + associate_public_ip_address  = (known after apply)
      + availability_zone            = (known after apply)
      + cpu_core_count               = (known after apply)
      + cpu_threads_per_core         = (known after apply)
      + get_password_data            = false
      + host_id                      = (known after apply)
      + id                           = (known after apply)
      + instance_state               = (known after apply)
      + instance_type                = "t2.micro"
      + ipv6_address_count           = (known after apply)
      + ipv6_addresses               = (known after apply)
      + key_name                     = (known after apply)
      + network_interface_id         = (known after apply)
      + outpost_arn                  = (known after apply)
      + password_data                = (known after apply)
      + placement_group              = (known after apply)
      + primary_network_interface_id = (known after apply)
      + private_dns                  = (known after apply)
      + private_ip                   = (known after apply)
      + public_dns                   = (known after apply)
      + public_ip                    = (known after apply)
      + security_groups              = (known after apply)
      + source_dest_check            = true
      + subnet_id                    = (known after apply)
      + tags                         = {
          + "Name" = "HelloWorld"
        }
      + tenancy                      = (known after apply)
      + volume_tags                  = (known after apply)
      + vpc_security_group_ids       = (known after apply)

      + ebs_block_device {
          + delete_on_termination = (known after apply)
          + device_name           = (known after apply)
          + encrypted             = (known after apply)
          + iops                  = (known after apply)
          + kms_key_id            = (known after apply)
          + snapshot_id           = (known after apply)
          + volume_id             = (known after apply)
          + volume_size           = (known after apply)
          + volume_type           = (known after apply)
        }

      + ephemeral_block_device {
          + device_name  = (known after apply)
          + no_device    = (known after apply)
          + virtual_name = (known after apply)
        }

      + metadata_options {
          + http_endpoint               = (known after apply)
          + http_put_response_hop_limit = (known after apply)
          + http_tokens                 = (known after apply)
        }

      + network_interface {
          + delete_on_termination = (known after apply)
          + device_index          = (known after apply)
          + network_interface_id  = (known after apply)
        }

      + root_block_device {
          + delete_on_termination = (known after apply)
          + device_name           = (known after apply)
          + encrypted             = (known after apply)
          + iops                  = (known after apply)
          + kms_key_id            = (known after apply)
          + volume_id             = (known after apply)
          + volume_size           = (known after apply)
          + volume_type           = (known after apply)
        }
    }

Plan: 1 to add, 0 to change, 0 to destroy.

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d basic_ec2`
* :put_litter_in_its_place: To **delete** this plan click [here](https://atlantis.kojie.cyou/lock?id=rcclemente%252Fterraform-atlantis-infra%252Fbasic_ec2%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -d basic_ec2`
</details>

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by rcclemente** [comment]
atlantis apply

**Comment by rcclemente** [comment]
Ran Apply for dir: `basic_ec2` workspace: `default`

**Apply Failed**: Pull request must be approved by at least one person other than the author before running apply.

**Review by qen — APPROVED** [review]

**Comment by rcclemente** [comment]
atlantis apply

**Comment by rcclemente** [comment]
Ran Apply for dir: `basic_ec2` workspace: `default`

**Apply Error**
```
running "/home/atlantis/.atlantis/bin/terraform0.12.25 apply -input=false -no-color \"/home/atlantis/.atlantis/repos/rcclemente/terraform-atlantis-infra/1/default/basic_ec2/default.tfplan\"" in "/home/atlantis/.atlantis/repos/rcclemente/terraform-atlantis-infra/1/default/basic_ec2": exit status 1
aws_instance.web: Creating...

Error: Error launching source instance: Unsupported: The requested configuration is currently not supported. Please check the documentation for supported configurations.
	status code: 400, request id: 07886144-d1b4-4bce-b1bb-b0fb036ce19f

  on main.tf line 1, in resource "aws_instance" "web":
   1: resource "aws_instance" "web" {



```

**Comment by rcclemente** [comment]
Ran Plan for dir: `basic_ec2` workspace: `default`

<details><summary>Show Output</summary>

```diff

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
+ create

Terraform will perform the following actions:

  # aws_instance.web will be created
+ resource "aws_instance" "web" {
      + ami                          = "ami-03e33c1cefd1d3d74"
      + arn                          = (known after apply)
      + associate_public_ip_address  = (known after apply)
      + availability_zone            = (known after apply)
      + cpu_core_count               = (known after apply)
      + cpu_threads_per_core         = (known after apply)
      + get_password_data            = false
      + host_id                      = (known after apply)
      + id                           = (known after apply)
      + instance_state               = (known after apply)
      + instance_type                = "t2.micro"
      + ipv6_address_count           = (known after apply)
      + ipv6_addresses               = (known after apply)
      + key_name                     = (known after apply)
      + network_interface_id         = (known after apply)
      + outpost_arn                  = (known after apply)
      + password_data                = (known after apply)
      + placement_group              = (known after apply)
      + primary_network_interface_id = (known after apply)
      + private_dns                  = (known after apply)
      + private_ip                   = (known after apply)
      + public_dns                   = (known after apply)
      + public_ip                    = (known after apply)
      + security_groups              = (known after apply)
      + source_dest_check            = true
      + subnet_id                    = (known after apply)
      + tags                         = {
          + "Name" = "HelloWorld"
        }
      + tenancy                      = (known after apply)
      + volume_tags                  = (known after apply)
      + vpc_security_group_ids       = (known after apply)

      + ebs_block_device {
          + delete_on_termination = (known after apply)
          + device_name           = (known after apply)
          + encrypted             = (known after apply)
          + iops                  = (known after apply)
          + kms_key_id            = (known after apply)
          + snapshot_id           = (known after apply)
          + volume_id             = (known after apply)
          + volume_size           = (known after apply)
          + volume_type           = (known after apply)
        }

      + ephemeral_block_device {
          + device_name  = (known after apply)
          + no_device    = (known after apply)
          + virtual_name = (known after apply)
        }

      + metadata_options {
          + http_endpoint               = (known after apply)
          + http_put_response_hop_limit = (known after apply)
          + http_tokens                 = (known after apply)
        }

      + network_interface {
          + delete_on_termination = (known after apply)
          + device_index          = (known after apply)
          + network_interface_id  = (known after apply)
        }

      + root_block_device {
          + delete_on_termination = (known after apply)
          + device_name           = (known after apply)
          + encrypted             = (known after apply)
          + iops                  = (known after apply)
          + kms_key_id            = (known after apply)
          + volume_id             = (known after apply)
          + volume_size           = (known after apply)
          + volume_type           = (known after apply)
        }
    }

Plan: 1 to add, 0 to change, 0 to destroy.

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d basic_ec2`
* :put_litter_in_its_place: To **delete** this plan click [here](https://atlantis.kojie.cyou/lock?id=rcclemente%252Fterraform-atlantis-infra%252Fbasic_ec2%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -d basic_ec2`
</details>

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by rcclemente** [comment]
atlantis apply

**Comment by rcclemente** [comment]
Ran Apply for dir: `basic_ec2` workspace: `default`

```diff
aws_instance.web: Creating...
aws_instance.web: Still creating... [10s elapsed]
aws_instance.web: Still creating... [20s elapsed]
aws_instance.web: Creation complete after 22s [id=i-0ae5d29cc198ead7e]

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.

```

**Comment by rcclemente** [comment]
Locks and plans deleted for the projects and workspaces modified in this pull request:

- dir: `basic_ec2` workspace: `default`

**Pull request merged**
